# Generated by Django 5.2.7 on 2025-10-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Le nom du magasin (ex: IGA, Metro, Maxi)', max_length=200, unique=True)),
                ('adresse', models.TextField(blank=True, help_text="L'adresse physique du magasin", null=True)),
                ('site_web', models.URLField(blank=True, help_text="L'URL du site web du magasin", null=True)),
            ],
            options={
                'verbose_name': 'Commerce',
                'verbose_name_plural': 'Commerces',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom complet du produit (ex: Lait 2% Natrel)', max_length=255)),
                ('marque', models.CharField(blank=True, help_text='La marque du produit (ex: Natrel)', max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, help_text='Catégorie du produit (ex: Produits Laitiers, Fruits et Légumes)', max_length=100, null=True)),
                ('code_barres', models.CharField(blank=True, help_text='Le code-barres UPC du produit', max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
