# Generated by Django 5.2.7 on 2025-10-31 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text='Date de début de validité de la circulaire')),
                ('date_fin', models.DateField(help_text='Date de fin de validité de la circulaire')),
                ('commerce', models.ForeignKey(help_text='Le commerce associé à cette circulaire', on_delete=django.db.models.deletion.CASCADE, to='core.commerce')),
            ],
            options={
                'verbose_name': 'Circulaire',
                'verbose_name_plural': 'Circulaires',
            },
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, help_text="Le prix de l'article", max_digits=10)),
                ('details_prix', models.CharField(blank=True, help_text="Détails additionnels (ex: '2 pour 5.00$', 'par livre')", max_length=100, null=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('circulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prix', to='core.circulaire')),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='core.commerce')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='core.produit')),
            ],
            options={
                'verbose_name': 'Prix',
                'verbose_name_plural': 'Prix',
            },
        ),
    ]
