# Generated by Django 5.2.7 on 2025-11-03 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_migrate_categories_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prix',
            name='confirmations',
            field=models.ManyToManyField(blank=True, related_name='confirmed_prices', to=settings.AUTH_USER_MODEL),
        ),
    ]
