# Generated by Django 5.2.7 on 2025-11-05 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_prix_confirmations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.IntegerField(default=0, help_text="Points de réputation de l'utilisateur")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('INCORRECT_PRICE', 'Prix incorrect'), ('WRONG_PRODUCT', 'Mauvais produit/commerce'), ('EXPIRED_DEAL', 'Rabais expiré'), ('OTHER', 'Autre')], max_length=50)),
                ('comments', models.TextField(blank=True, help_text='Commentaires additionnels (optionnel)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('REVIEWED', 'Examiné'), ('RESOLVED', 'Résolu')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.prix')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('price_entry', 'reported_by')},
            },
        ),
    ]
