# Generated by Django 5.2.7 on 2025-11-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inventory_layout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
