# Generated by Django 5.2.7 on 2025-11-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_inventory_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='inventory_layout',
        ),
        migrations.AddField(
            model_name='profile',
            name='layouts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
