# Generated by Django 5.2.7 on 2025-11-16 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_migrate_inventory_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='alert_threshold',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
