# Generated by Django 5.2.7 on 2025-11-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_inventoryitem_alert_threshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='order',
            field=models.IntegerField(default=0, help_text="Définit l'ordre d'affichage de l'article"),
        ),
    ]
