"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dotenv # Importer dotenv
import dj_database_url # Importer dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv.load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# LIRE LA SECRET_KEY DEPUIS LE FICHIER .env
SECRET_KEY = os.getenv('SECRET_KEY')

# LIRE LA VALEUR DEBUG DEPUIS LE FICHIER .env
# Le 'True' est une valeur par défaut si la variable n'est pas trouvée
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['maptool.temis.qc.ca', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'rest_framework.authtoken',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CONFIGURATION DES E-MAILS (DÉVELOPPEMENT) ---
# Indique à Django d'afficher les e-mails dans la console au lieu de les envoyer.
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')

INTERNAL_IPS = [
    "127.0.0.1",
]

# --- CONFIGURATION DES REDIRECTIONS ---
# URL vers laquelle rediriger l'utilisateur après une connexion réussie.
# '/' correspond à la racine de votre site (la page 'assistant_epicerie').
LOGIN_REDIRECT_URL = '/'

# --- CONFIGURATION DE DJANGO REST FRAMEWORK ---
REST_FRAMEWORK = {
    # On définit les méthodes d'authentification par défaut pour toutes les vues de l'API.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Privilégie l'authentification par jeton (Token), idéale pour les API consommées par du JS.
        'rest_framework.authentication.TokenAuthentication',
        # Garde l'authentification par session comme alternative (utile pour l'API explorable).
        'rest_framework.authentication.SessionAuthentication',
    ],
    # On peut aussi définir une politique de permission par défaut pour plus de sécurité.
    # Ceci exigera que l'utilisateur soit authentifié pour toutes les vues API,
    # sauf si une vue spécifie le contraire.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}
